name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set-up Node 
        uses: actions/setup-node@v1
          with:
            node-version: "16.13.x"
      - name: Install packages
        run: yarn install      
      - name: Prettier format
        run: |
          yarn format
      - name: Eslint Lint
        run: yarn lint
      - name: Deploy Github Pages
        run: 
            crazy-max/ghaction-github-pages@v1
          with:
            target_branch: gh-pages
            build_dir: build
          env: 
            GITHUB_TOKEN:
              ${{ secrets.GITHUBCI }}
